spring:
  datasource:
    name: TestConnection  #数据库名
    url: jdbc:mysql://localhost:3306/gdms_database?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8 #url
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.jdbc.Driver #数据库链接驱动

    #配置easyPoi允许旧bean被新bean代替
  application:
      name: SpringBoot_easyPOI

  main:
      allow-bean-definition-overriding: true


    #配置服务端口（使用main方法启动）；
server:
  port: 8082

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check